version: '3.7'

services:
    web:
        build:
            context: infrastructure/docker
            dockerfile: web/Dockerfile
        volumes:
            - ./${APP_DIRECTORY_NAME}:/var/www:ro
        ports:
            - 8085:80
        depends_on:
            - php

    php:
        build:
            context: infrastructure/docker
            dockerfile: php/Dockerfile
        volumes:
            - ./${APP_DIRECTORY_NAME}:/var/www
        depends_on:
            - db

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - 3306:3306
